version: '3.4'
services:
  web-test:
    build: 
      context: web
      dockerfile: ci-test/Dockerfile
    ports:
    - "8080:8080"
    - "9998:9998"
    container_name: dictionary-web-test

networks:
  dictionary-network:
