version: '3.4'
services:
  web:
    build:
      context: ../web
    ports:
    - "80:80"
    - "8787:8787"
    container_name: dictionary-web
    networks:
    - dictionary-network 
  mom:
    build: ../mom
    ports:
    - "8081:8081"
    - "9990:9990"
    container_name: mom
    networks:
    - dictionary-network
  backoffice:
    build: ../backoffice
    ports:
    - "8082:8082"
    container_name: backoffice
    networks:
    - dictionary-network

  web-test:
    build: 
      context: ../web
      dockerfile: ci-test/Dockerfile
    ports:
    - "8080:8080"
    - "9998:9998"
    container_name: dictionary-web-test
  mariadb:
    image: mariadb:10.8.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: dictionary
    ports:
    -  "3306:3306"
    container_name: mariadb
    networks:
    - dictionary-network
networks:
  dictionary-network:
