version: '3.4'
services:
  rest-api:
    build:
      context: ../dictionary-mod-jpa
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    container_name: dictionary-web
    networks:
    - dictionary-network
 
  backoffice:
    build: ../backoffice
    ports:
    - "8082:8082"
    container_name: backoffice
    networks:
    - dictionary-network

  dictionary-postgresql-db:
    image: postgres:17.5-alpine3.22
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
    container_name: dictionary-db
    networks:
    - dictionary-network
networks:
  dictionary-network:
