version: '3.4'
services:
  web:
    build: ../web
    ports:
    - "80:80"
    - "8787:8787"
    container_name: dictionary-web
  mom:
    build: ../mom
    ports:
    - "8081:8081"
    - "9990:9990"
    container_name: mom
    networks:
      dictionary-network:
        ipv4_address: 172.22.0.2
  backoffice:
    build: ../backoffice
    ports:
    - "8082:8082"
    - "9991:9991"
    container_name: backoffice
    networks:
      dictionary-network:
        ipv4_address: 172.22.0.3


networks:
  dictionary-network:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/16"
