version: '3.4'

services:
  web:
    build: ../web
    ports: 
    - "80:80"
    - "8787:8787"
    container_name: dictionary-web
  mom:
    build: ../mom
    ports: 
    - "8081:8081"
    container_name: message-queue

