version: '3.4'
services:
  web:
    build: ../web
    ports:
    - "80:80"
    - "8787:8787"
    container_name: dictionary-web
  mom:
    build: ../mom
    ports:
    - "8081:8081"
    - "9990:9990"
    container_name: mom
    networks:
    - dictionary-network
  backoffice:
    build: ../backoffice
    ports:
    - "8082:8082"
    container_name: backoffice
    networks:
    - dictionary-network

networks:
  dictionary-network:
