--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(1, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'crux','en_US','N');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(2, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'take','en_US','N');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(3, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'take','en_US','VT');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(4, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'palapeli','fi','N');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(5, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'jodi','fi','N');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(6, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'vaikku','fi','N');
--INSERT INTO entry (id, createdDate, entry,language, poS) VALUES(7, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'kaluste','fi','N');
-- DEFINTION
--INSERT INTO definition VALUES(1, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'the most important point','en_US', 1);
--INSERT INTO definition VALUES(2, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), '看法，观点，意见','zh_CN', 2);
--INSERT INTO definition VALUES(3, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), '拿','zh_CN', 3);
--INSERT INTO definition VALUES(4, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), '执行','zh_CN', 3);
--INSERT INTO definition VALUES(5, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), '关键','zh_CN', 1);
--INSERT INTO definition VALUES(6, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), 'wax','zh_EN', 5);
--INSERT INTO definition VALUES(7, PARSEDATETIME('17-04-2022', 'dd-MM-yyyy'), '家具','zh_CN', 6);