FROM quay.io/wildfly/wildfly:27.0.0.Final-jdk17
COPY java/app/target/dictionary.war /opt/jboss/wildfly/standalone/deployments/
COPY docker_config/standalone.conf /opt/jboss/wildfly/bin/
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-c", "standalone.xml", "-Djboss.http.port=${PORT}", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
