on: [push]

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: CI Test
    steps:
      - name: Start Wildfly container for integration test
        id: start-wildfly
        uses: rxue/dictionary/web/ci-test@master
        run: echo "test only for trial"
        #  who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Run Python script
        run: python3 -m unittest discover -s uat/
