on: [push]

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: CI Test
    steps:
      - name: Start Wildfly Docker container
        uses: rxue/dictionary/web/ci-test@master
      - name: Test
        run: echo "test Wildfly"
