on: [push]

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: CI Test
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: start Docker container with Dockerfile for CI test
        run: |
          cd docker
          source run_ci_test_web.sh
