on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: CI Test
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup JDK Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: start Docker container with Dockerfile and run REST API test by using the container
        run: |
          cd docker
          source rest_test.sh
