# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy Docker image to Azure App Service

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  build-and-deploy:

    runs-on: ubuntu-latest  
    environment: DEPLOYMENT_2_AZURE
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print to debug GitHub OIDC subject
      run: echo "Subject: repo=${{ github.repository }} ref=${{ github.ref }}"

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-oidc: true

    - name: Deploy Docker image to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: dictionary-rest-api
        images: ${{ secrets.DOCKERHUB_USERNAME }}/dictionary-rest-api:1.0
