# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Push Docker image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag of the image"
        required: true
        default: 'latest'
jobs:
  build:

    runs-on: ubuntu-latest
    environment: DOCKER_IMAGE_DEPLOYMENT
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Submodule
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build dictionary-mod-jpa module
      run: mvn -B --file dictionary-mod-jpa/pom.xml clean package -Dquarkus.package.jar.type=legacy-jar

    - name: Copy the Dockerfile to the context directory so that it can be built
      run: cp dictionary-mod-jpa/src/main/docker/Dockerfile.legacy-jar dictionary-mod-jpa/Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and then push Docker image
      uses: docker/build-push-action@v5
      with:
          context: ./dictionary-mod-jpa
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dictionary-rest-api:${{ inputs.tag }}
          push: true   # true if you want to push to Docker Hub or registry
